export const onboardingTourSteps = [
  {
    id: "nav-help",
    route: null,
    targetId: "nav-help",
    title: "Reopen the guided tour any time",
    body: "Use this help button whenever you want to replay the walkthrough from the beginning.",
    placement: "bottom",
  },
  {
    id: "nav-pages",
    route: null,
    targetId: "nav-pages",
    title: "The app follows one flow",
    body: "You move through Setup, then Generate, then Views. The tour will take you across those pages automatically.",
    placement: "bottom",
  },
  {
    id: "setup-header",
    route: "/setup",
    targetId: "setup-header",
    title: "Setup builds the working snapshot",
    body: "Start from student enrolments, then add support CSVs and repair only the missing local issues.",
    placement: "bottom",
  },
  {
    id: "setup-enrollment-import",
    route: "/setup",
    targetId: "setup-enrollment-import",
    title: "Student enrolments create the snapshot",
    body: "This import defines the student-module truth and is the first thing you do before adding rooms, lecturers, or sessions.",
    placement: "right",
  },
  {
    id: "setup-support-imports",
    route: "/setup",
    targetId: "setup-support-imports",
    title: "Support CSVs enrich the snapshot",
    body: "After the enrolment snapshot exists, import rooms, lecturers, modules, sessions, and session-lecturer links here.",
    placement: "top",
  },
  {
    id: "setup-readiness",
    route: "/setup",
    targetId: "setup-readiness",
    title: "Readiness separates imports from repairs",
    body: "This section tells you what must still be imported and what can be repaired locally before generation can run.",
    placement: "top",
  },
  {
    id: "setup-continue",
    route: "/setup",
    targetId: "setup-continue",
    title: "Move to generation when setup is ready",
    body: "Once the blocking requirements are cleared, this button takes the current snapshot into Generate.",
    placement: "left",
  },
  {
    id: "generate-run-button",
    route: "/generate",
    targetId: "generate-run-button",
    title: "Generate timetables from the current snapshot",
    body: "This runs the solver using the setup you prepared in the previous page.",
    placement: "left",
  },
  {
    id: "generate-preferences",
    route: "/generate",
    targetId: "generate-preferences",
    title: "Preferences are optional",
    body: "Start broad. Add nice-to-have preferences only when you want the system to narrow a large solution set.",
    placement: "bottom",
  },
  {
    id: "generate-results",
    route: "/generate",
    targetId: "generate-results",
    title: "Results and verification appear here",
    body: "After a run, this area shows solution counts, verification, and the default timetable that Views will open.",
    placement: "top",
  },
  {
    id: "views-mode-controls",
    route: "/views",
    targetId: "views-mode-controls",
    title: "Switch between admin, lecturer, and student views",
    body: "Use these controls to move between the full timetable and filtered audience-specific views.",
    placement: "bottom",
  },
  {
    id: "views-export-controls",
    route: "/views",
    targetId: "views-export-controls",
    title: "Export the current timetable view",
    body: "Once the result looks right, export it in the format you need from here.",
    placement: "left",
  },
];

