export const BASIC_TOUR = "basic";
export const TECHNICAL_TOUR = "technical";

export const onboardingTourSteps = {
  [BASIC_TOUR]: [
    {
      id: "nav-help",
      route: null,
      targetId: "nav-help",
      title: "Reopen the guided tour any time",
      body: "Use this help menu whenever you want to replay the basic walkthrough or explicitly start the technical one.",
      placement: "bottom",
    },
    {
      id: "nav-pages",
      route: null,
      targetId: "nav-pages",
      title: "The app follows one flow",
      body: "You move through Setup, then Generate, then Views. The tour will take you across those pages automatically.",
      placement: "bottom",
    },
    {
      id: "setup-header",
      route: "/setup",
      targetId: "setup-header",
      title: "Setup builds the working snapshot",
      body: "Start from student enrolments, then add support CSVs and repair only the missing local issues.",
      placement: "bottom",
    },
    {
      id: "setup-enrollment-import",
      route: "/setup",
      targetId: "setup-enrollment-import",
      title: "Student enrolments create the snapshot",
      body: "This import defines the student-module truth and is the first thing you do before adding rooms, lecturers, or sessions.",
      placement: "right",
    },
    {
      id: "setup-support-imports",
      route: "/setup",
      targetId: "setup-support-imports",
      title: "Support CSVs enrich the snapshot",
      body: "After the enrolment snapshot exists, import rooms, lecturers, modules, sessions, and session-lecturer links here.",
      placement: "top",
    },
    {
      id: "setup-readiness",
      route: "/setup",
      targetId: "setup-readiness",
      title: "Readiness separates imports from repairs",
      body: "This section tells you what must still be imported and what can be repaired locally before generation can run.",
      placement: "top",
    },
    {
      id: "setup-continue",
      route: "/setup",
      targetId: "setup-continue",
      title: "Move to generation when setup is ready",
      body: "Once the blocking requirements are cleared, this button takes the current snapshot into Generate.",
      placement: "left",
    },
    {
      id: "generate-run-button",
      route: "/generate",
      targetId: "generate-run-button",
      title: "Generate timetables from the current snapshot",
      body: "This runs the solver using the setup you prepared in the previous page.",
      placement: "left",
    },
    {
      id: "generate-preferences",
      route: "/generate",
      targetId: "generate-preferences",
      title: "Preferences are optional",
      body: "Start broad. Add nice-to-have preferences only when you want the system to narrow a large solution set.",
      placement: "bottom",
    },
    {
      id: "generate-results",
      route: "/generate",
      targetId: "generate-results",
      title: "Results and verification appear here",
      body: "After a run, this area shows solution counts, verification, and the default timetable that Views will open.",
      placement: "top",
    },
    {
      id: "views-mode-controls",
      route: "/views",
      targetId: "views-mode-controls",
      title: "Switch between admin, lecturer, and student views",
      body: "Use these controls to move between the full timetable and filtered audience-specific views.",
      placement: "bottom",
    },
    {
      id: "views-export-controls",
      route: "/views",
      targetId: "views-export-controls",
      title: "Export the current timetable view",
      body: "Once the result looks right, export it in the format you need from here.",
      placement: "left",
    },
  ],
  [TECHNICAL_TOUR]: [
    {
      id: "nav-help-technical",
      route: null,
      targetId: "nav-help",
      title: "Use the help menu to choose the tour type",
      body: "The basic walkthrough is for first-time orientation. The technical walkthrough is an explicit power-user path and never auto-opens.",
      placement: "bottom",
    },
    {
      id: "nav-pages-technical",
      route: null,
      targetId: "nav-pages",
      title: "The app still runs in one strict order",
      body: "Setup creates or repairs the snapshot, Generate solves from that snapshot, and Views only reads the selected default timetable.",
      placement: "bottom",
    },
    {
      id: "setup-header-technical",
      route: "/setup",
      targetId: "setup-header",
      title: "Setup is where source data becomes solver-ready structure",
      body: "This page is not a spreadsheet editor. Its job is to turn imported data into a coherent snapshot, expose gaps honestly, and let you fix only the local issues that matter for generation.",
      placement: "bottom",
    },
    {
      id: "setup-enrollment-technical",
      route: "/setup",
      targetId: "setup-enrollment-import",
      title: "Student enrolments define the canonical structure",
      body: "This is the only import that creates the academic snapshot. Programmes, paths, module memberships, and attendance truth all start here.",
      placement: "right",
    },
    {
      id: "setup-enrollment-analysis-technical",
      route: "/setup",
      targetId: "setup-enrollment-import",
      title: "Analyze, review, then use the import",
      body: "Enrollment import is intentionally slower and more opinionated than the support CSVs. The system analyzes ambiguity first, lets you decide how to interpret it, then materializes the reviewed result into the real snapshot.",
      placement: "right",
    },
    {
      id: "setup-review-buckets",
      route: "/setup",
      targetId: "setup-review-buckets",
      fallbackTargetId: "setup-enrollment-import",
      title: "Review buckets are ambiguity controls, not hard errors",
      body: "Use the default action for the broad pattern, then override only the suspicious buckets. This is where you resolve import ambiguity before materializing the snapshot.",
      placement: "bottom",
    },
    {
      id: "setup-review-strategy",
      route: "/setup",
      targetId: "setup-review-buckets",
      fallbackTargetId: "setup-enrollment-import",
      title: "The fast path is bulk default plus targeted overrides",
      body: "The intended workflow is not one-by-one adjudication of every bucket. Pick a default for the dominant pattern, sort by row count, and override only the buckets that would materially distort attendance truth or teaching structure.",
      placement: "bottom",
    },
    {
      id: "setup-support-imports-technical",
      route: "/setup",
      targetId: "setup-support-imports",
      title: "Support CSVs enrich an existing snapshot",
      body: "Rooms, lecturers, modules, sessions, and session-lecturer links are applied against the materialized snapshot. They cannot stand alone before enrolments are used.",
      placement: "top",
    },
    {
      id: "setup-support-imports-semantics",
      route: "/setup",
      targetId: "setup-support-imports",
      title: "Each support CSV contributes different solver-facing semantics",
      body: "Rooms contribute capacity and capability constraints. Lecturers contribute staffing identities. Modules can refine metadata. Sessions define actual teachable events. Session-lecturer links attach staffing to those events.",
      placement: "top",
    },
    {
      id: "setup-readiness-technical",
      route: "/setup",
      targetId: "setup-readiness",
      title: "Readiness separates import gaps from repair gaps",
      body: "Import-needed issues mean a whole relationship set is missing. Repair-needed issues mean the records exist but local links or constraints still need correction.",
      placement: "top",
    },
    {
      id: "setup-readiness-model-semantics",
      route: "/setup",
      targetId: "setup-readiness",
      title: "This is where missing schemas and broken relationships diverge",
      body: "A missing `rooms.csv` is a missing relationship set. A session with no lecturer links or no attendance groups is a broken local relationship. That distinction is why the setup UI can stay minimal without pretending every issue should be fixed by reimport.",
      placement: "top",
    },
    {
      id: "setup-repair-queue-technical",
      route: "/setup",
      targetId: "setup-repair-queue",
      fallbackTargetId: "setup-readiness",
      title: "Repair queue is for local corrections, not bulk authoring",
      body: "Use this queue for small solver-relevant fixes such as missing lecturer links, missing attendance mappings, room mismatches, or incomplete session definitions. If the source data is broadly wrong, fix the CSV and reimport instead.",
      placement: "top",
    },
    {
      id: "setup-utilities-technical",
      route: "/setup",
      targetId: "setup-utilities",
      fallbackTargetId: "setup-header",
      title: "Templates, fixture packs, and previous snapshots serve different jobs",
      body: "Templates teach the schema. Fixture packs give you realistic importable test data. Previous snapshots are a technical shortcut when you want to continue from an earlier run.",
      placement: "bottom",
    },
    {
      id: "setup-utilities-open-state",
      route: "/setup",
      targetId: "setup-utilities",
      fallbackTargetId: "setup-header",
      title: "Utilities should stay secondary, but the technical tour opens them for inspection",
      body: "In normal use this section stays collapsed so the default mental model is 'start fresh and import again'. The technical tour expands it deliberately so you can inspect the fixture-pack and previous-snapshot tools in context.",
      placement: "bottom",
    },
    {
      id: "setup-fixture-pack-technical",
      route: "/setup",
      targetId: "setup-fixture-pack",
      fallbackTargetId: "setup-utilities",
      title: "Fixture packs are for realistic testing, not schema learning",
      body: "The production-like fixture pack is the closest thing to a full sample deployment dataset. It exists so you can test import, readiness, generation, and export flows from files instead of magic demo buttons or UI-only seeding.",
      placement: "bottom",
    },
    {
      id: "generate-run-technical",
      route: "/generate",
      targetId: "generate-run-button",
      title: "Generation always uses the current snapshot directly",
      body: "The solver reads the normalized snapshot state, not the raw CSVs. That is why setup correctness matters more than import completion alone.",
      placement: "left",
    },
    {
      id: "generate-run-state-technical",
      route: "/generate",
      targetId: "generate-run-button",
      title: "Generation is a snapshot solve, not a page-local action",
      body: "The button runs against the currently active import snapshot. If the wrong snapshot is active, or if readiness is misleading, you will generate against the wrong world even if the button itself works perfectly.",
      placement: "left",
    },
    {
      id: "generate-preferences-technical",
      route: "/generate",
      targetId: "generate-preferences",
      title: "Preferences are soft constraints, not required inputs",
      body: "These settings narrow the solution space. They should not be used to compensate for missing rooms, lecturers, or broken session definitions.",
      placement: "top",
    },
    {
      id: "generate-preferences-strategy",
      route: "/generate",
      targetId: "generate-preferences",
      title: "Start broad, then constrain only when the solution set is too large",
      body: "Soft constraints are for preference shaping. A good workflow is to prove feasibility first, inspect how large the valid solution space is, then use preferences to reduce that space without accidentally masking a setup defect.",
      placement: "top",
    },
    {
      id: "generate-combinations-technical",
      route: "/generate",
      targetId: "generate-combinations",
      fallbackTargetId: "generate-results",
      title: "Combination suggestions are fallback guidance when preferences conflict",
      body: "If the selected preference set cannot be satisfied together, the app suggests smaller compatible combinations. That is not a solver failure. It is a way to recover from an over-constrained nice-to-have set without weakening hard requirements.",
      placement: "top",
    },
    {
      id: "generate-verification-technical",
      route: "/generate",
      targetId: "generate-verification",
      fallbackTargetId: "generate-results",
      title: "Verification is a separate trust check",
      body: "Generation finds candidate timetables. Verification checks the selected result against the normalized snapshot. Python is built in; Rust and Elixir are optional extra verifiers.",
      placement: "top",
    },
    {
      id: "generate-verification-trust-model",
      route: "/generate",
      targetId: "generate-verification",
      fallbackTargetId: "generate-results",
      title: "Trust level depends on completed verifiers, not only on solver success",
      body: "A solver run can succeed and still not be fully trusted if some verifier runtimes are unavailable. Hard-constraint pass, missing verifiers, and default-solution status should be read together rather than as separate cosmetic indicators.",
      placement: "top",
    },
    {
      id: "generate-preview-solutions-technical",
      route: "/generate",
      targetId: "generate-preview-solutions",
      fallbackTargetId: "generate-results",
      title: "Preview solutions are candidate outputs, not independent datasets",
      body: "All preview solutions come from the same snapshot and soft-constraint context. Setting one as default is a product decision about which valid result becomes the canonical timetable for Views and export.",
      placement: "top",
    },
    {
      id: "views-mode-technical",
      route: "/views",
      targetId: "views-mode-controls",
      title: "Views are filtered projections of the selected timetable",
      body: "Admin shows the full default timetable. Lecturer and student modes filter that same timetable rather than generating new ones.",
      placement: "bottom",
    },
    {
      id: "views-selection-mechanics",
      route: "/views",
      targetId: "views-mode-controls",
      title: "Lecturer and student views depend on lookup-driven selection, not separate datasets",
      body: "Those selectors are populated from the active snapshot. They narrow the same accepted timetable by lecturer, degree, year, and path, which is why bad setup metadata will surface here as missing or misleading filters.",
      placement: "bottom",
    },
    {
      id: "views-layout-technical",
      route: "/views",
      targetId: "views-layout-controls",
      title: "Calendar and agenda are two representations of the same timetable entries",
      body: "Calendar emphasizes spatial overlap and time placement. Agenda emphasizes scanability and textual review. Switching layout changes presentation, not the underlying timetable data.",
      placement: "bottom",
    },
    {
      id: "views-density-technical",
      route: "/views",
      targetId: "views-density-controls",
      title: "Density only changes rendering density, not timetable granularity",
      body: "Compact, comfortable, and expanded change how much vertical space the day view consumes. They are reading aids for humans, not solver parameters and not export controls.",
      placement: "bottom",
    },
    {
      id: "views-day-picker-technical",
      route: "/views",
      targetId: "views-day-picker",
      fallbackTargetId: "views-calendar-surface",
      title: "Day selection is part of the admin inspection workflow",
      body: "The day picker is where you inspect weekly spread, room contention patterns, and whether repeated sessions are bunched badly across the week. It is not just a navigation convenience.",
      placement: "top",
    },
    {
      id: "views-calendar-surface-technical",
      route: "/views",
      targetId: "views-calendar-surface",
      title: "This surface is where schedule quality becomes obvious",
      body: "Dense stacks, awkward spacing, and suspicious room or lecturer usage are much easier to notice here than in raw exports. Technical users should treat this page as a visual QA layer before export.",
      placement: "top",
    },
    {
      id: "views-mode-audience-semantics",
      route: "/views",
      targetId: "views-mode-controls",
      title: "Audience views are read models, not new solver runs",
      body: "Changing modes affects presentation and filtering only. It does not change solver truth, session semantics, or the selected default timetable underneath.",
      placement: "bottom",
    },
    {
      id: "views-export-technical",
      route: "/views",
      targetId: "views-export-controls",
      title: "Exports are the handoff layer back to external systems",
      body: "Once a timetable is accepted, exports are how you round-trip it out of this app. That makes setup and verification decisions upstream operationally important.",
      placement: "left",
    },
    {
      id: "views-export-operations",
      route: "/views",
      targetId: "views-export-controls",
      title: "Export is the operational endpoint of the workflow",
      body: "This app does not connect directly to the external main system. The practical contract is import external data, normalize and solve it here, then export the accepted result back out in a usable format.",
      placement: "left",
    },
  ],
};
