export const BASIC_TOUR = "basic";
export const TECHNICAL_TOUR = "technical";

export const onboardingTourSteps = {
  [BASIC_TOUR]: [
    {
      id: "nav-help",
      route: null,
      targetId: "nav-help",
      title: "Reopen the guided tour any time",
      body: "Use this help menu whenever you want to replay the basic walkthrough or explicitly start the technical one.",
      placement: "bottom",
    },
    {
      id: "nav-pages",
      route: null,
      targetId: "nav-pages",
      title: "The app follows one flow",
      body: "You move through Setup, then Generate, then Views. The tour will take you across those pages automatically.",
      placement: "bottom",
    },
    {
      id: "setup-header",
      route: "/setup",
      targetId: "setup-header",
      title: "Setup builds the working snapshot",
      body: "Start from student enrolments, then add support CSVs and repair only the missing local issues.",
      placement: "bottom",
    },
    {
      id: "setup-enrollment-import",
      route: "/setup",
      targetId: "setup-enrollment-import",
      title: "Student enrolments create the snapshot",
      body: "This import defines the student-module truth and is the first thing you do before adding rooms, lecturers, or sessions.",
      placement: "right",
    },
    {
      id: "setup-support-imports",
      route: "/setup",
      targetId: "setup-support-imports",
      title: "Support CSVs enrich the snapshot",
      body: "After the enrolment snapshot exists, import rooms, lecturers, modules, sessions, and session-lecturer links here.",
      placement: "top",
    },
    {
      id: "setup-readiness",
      route: "/setup",
      targetId: "setup-readiness",
      title: "Readiness separates imports from repairs",
      body: "This section tells you what must still be imported and what can be repaired locally before generation can run.",
      placement: "top",
    },
    {
      id: "setup-continue",
      route: "/setup",
      targetId: "setup-continue",
      title: "Move to generation when setup is ready",
      body: "Once the blocking requirements are cleared, this button takes the current snapshot into Generate.",
      placement: "left",
    },
    {
      id: "generate-run-button",
      route: "/generate",
      targetId: "generate-run-button",
      title: "Generate timetables from the current snapshot",
      body: "This runs the solver using the setup you prepared in the previous page.",
      placement: "left",
    },
    {
      id: "generate-preferences",
      route: "/generate",
      targetId: "generate-preferences",
      title: "Preferences are optional",
      body: "Start broad. Add nice-to-have preferences only when you want the system to narrow a large solution set.",
      placement: "bottom",
    },
    {
      id: "generate-results",
      route: "/generate",
      targetId: "generate-results",
      title: "Results and verification appear here",
      body: "After a run, this area shows solution counts, verification, and the default timetable that Views will open.",
      placement: "top",
    },
    {
      id: "views-mode-controls",
      route: "/views",
      targetId: "views-mode-controls",
      title: "Switch between admin, lecturer, and student views",
      body: "Use these controls to move between the full timetable and filtered audience-specific views.",
      placement: "bottom",
    },
    {
      id: "views-export-controls",
      route: "/views",
      targetId: "views-export-controls",
      title: "Export the current timetable view",
      body: "Once the result looks right, export it in the format you need from here.",
      placement: "left",
    },
  ],
  [TECHNICAL_TOUR]: [
    {
      id: "nav-help-technical",
      route: null,
      targetId: "nav-help",
      title: "Use the help menu to choose the tour type",
      body: "The basic walkthrough is for first-time orientation. The technical walkthrough is an explicit power-user path and never auto-opens.",
      placement: "bottom",
    },
    {
      id: "nav-pages-technical",
      route: null,
      targetId: "nav-pages",
      title: "The app still runs in one strict order",
      body: "Setup creates or repairs the snapshot, Generate solves from that snapshot, and Views only reads the selected default timetable.",
      placement: "bottom",
    },
    {
      id: "setup-enrollment-technical",
      route: "/setup",
      targetId: "setup-enrollment-import",
      title: "Student enrolments define the canonical structure",
      body: "This is the only import that creates the academic snapshot. Programmes, paths, module memberships, and attendance truth all start here.",
      placement: "right",
    },
    {
      id: "setup-review-buckets",
      route: "/setup",
      targetId: "setup-review-buckets",
      fallbackTargetId: "setup-enrollment-import",
      title: "Review buckets are ambiguity controls, not hard errors",
      body: "Use the default action for the broad pattern, then override only the suspicious buckets. This is where you resolve import ambiguity before materializing the snapshot.",
      placement: "bottom",
    },
    {
      id: "setup-support-imports-technical",
      route: "/setup",
      targetId: "setup-support-imports",
      title: "Support CSVs enrich an existing snapshot",
      body: "Rooms, lecturers, modules, sessions, and session-lecturer links are applied against the materialized snapshot. They cannot stand alone before enrolments are used.",
      placement: "top",
    },
    {
      id: "setup-readiness-technical",
      route: "/setup",
      targetId: "setup-readiness",
      title: "Readiness separates import gaps from repair gaps",
      body: "Import-needed issues mean a whole relationship set is missing. Repair-needed issues mean the records exist but local links or constraints still need correction.",
      placement: "top",
    },
    {
      id: "setup-utilities-technical",
      route: "/setup",
      targetId: "setup-utilities",
      fallbackTargetId: "setup-header",
      title: "Templates, fixture packs, and previous snapshots serve different jobs",
      body: "Templates teach the schema. Fixture packs give you realistic importable test data. Previous snapshots are a technical shortcut when you want to continue from an earlier run.",
      placement: "bottom",
    },
    {
      id: "generate-run-technical",
      route: "/generate",
      targetId: "generate-run-button",
      title: "Generation always uses the current snapshot directly",
      body: "The solver reads the normalized snapshot state, not the raw CSVs. That is why setup correctness matters more than import completion alone.",
      placement: "left",
    },
    {
      id: "generate-preferences-technical",
      route: "/generate",
      targetId: "generate-preferences",
      title: "Preferences are soft constraints, not required inputs",
      body: "These settings narrow the solution space. They should not be used to compensate for missing rooms, lecturers, or broken session definitions.",
      placement: "top",
    },
    {
      id: "generate-verification-technical",
      route: "/generate",
      targetId: "generate-verification",
      fallbackTargetId: "generate-results",
      title: "Verification is a separate trust check",
      body: "Generation finds candidate timetables. Verification checks the selected result against the normalized snapshot. Python is built in; Rust and Elixir are optional extra verifiers.",
      placement: "top",
    },
    {
      id: "views-mode-technical",
      route: "/views",
      targetId: "views-mode-controls",
      title: "Views are filtered projections of the selected timetable",
      body: "Admin shows the full default timetable. Lecturer and student modes filter that same timetable rather than generating new ones.",
      placement: "bottom",
    },
    {
      id: "views-export-technical",
      route: "/views",
      targetId: "views-export-controls",
      title: "Exports are the handoff layer back to external systems",
      body: "Once a timetable is accepted, exports are how you round-trip it out of this app. That makes setup and verification decisions upstream operationally important.",
      placement: "left",
    },
  ],
};
